version: "3.9"

services:
  web:
    container_name: ${WEB_CONTAINER_NAME}
    build:
      context: ./web
      dockerfile: ./Dockerfile.prod
      args: 
        VITE_BASE_ENDPOINT: ${VITE_BASE_ENDPOINT}
        VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - cms
    networks:
      - front
  cms:
    container_name: ${CMS_CONTAINER_NAME}
    build:
      context: ./cms
      dockerfile: ./Dockerfile.prod
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGO_CONTAINER_NAME=${MONGO_CONTAINER_NAME}
      - MONGODB_URL=${MONGODB_URL}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - PAYLOAD_PORT=${PAYLOAD_PORT}
      - PAYLOAD_SERVER_URL=${PAYLOAD_SERVER_URL}`
    depends_on:
      - mongo
    networks:
      - back
      - front
  mongo:
    container_name: ${MONGO_CONTAINER_NAME}
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/data/db
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'