version: "3.9"

services:
  web:
    container_name: ${WEB_CONTAINER_NAME}
    build:
      context: ./web
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./web/src:/usr/app/src
    environment:
      - VITE_BASE_ENDPOINT=${VITE_BASE_ENDPOINT}
      - VITE_API_ENDPOINT=${VITE_API_ENDPOINT}
    network_mode: host
    depends_on:
      - cms
  cms:
    container_name: ${CMS_CONTAINER_NAME}
    build:
      context: ./cms
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./cms/src:/usr/app/src
    environment:
      - MONGO_CONTAINER_NAME=${MONGO_CONTAINER_NAME}
      - MONGODB_URL=${MONGODB_URL}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - PAYLOAD_PORT=${PAYLOAD_PORT}
      - PAYLOAD_SERVER_URL=${PAYLOAD_SERVER_URL}
    depends_on:
      - mongo
  mongo:
    container_name: ${MONGO_CONTAINER_NAME}
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/data/db

    