FROM node:17-alpine AS builder

WORKDIR /app

RUN apk add python3 make g++

COPY package.json package-lock.json ./

COPY . .

RUN npm ci

ENV NODE_ENV production

RUN npm run build


FROM node:17-alpine

WORKDIR /app

USER node:node

COPY --from=builder --chown=node:node /app/ ./

ENV PORT 3001
EXPOSE 3001

CMD ["npm", "run", "serve"]